### ISSUE TITLE
以 markdown 等格式匯出課程指引/討論串內容

### ISSUE THREAD

**Issue by skyhong2002** [JacobLinCool/moodle-backup#3]
有鑒於部分課程老師期望的繳交方式是以在討論串下留言的方式，但目前尚未不支援匯出這些資料。
或許以 markdown 匯出自己有回覆的討論串/貼文內容及自己的回覆能解決。

嗚嗚嗚這個好好用

**Comment by JacobLinCool** [comment]
新版本已支援匯出 markdown 格式的論壇資料（不包括附件檔案），以及其他課程資源（放在首頁的講義、簡報等）。
